/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/2025-mercedes-benz-g-class-amg-g-63-f583b5bfc17346c08573dc4f1edebefe
Title: 2025 Mercedes-Benz G-Class AMG G 63
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mercedes_G_class(props) {
  const { nodes, materials } = useGLTF('/3dassets/cars/2025_mercedes-benz_g-class_amg_g_63.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.8} position={[-0.2, -1, -2]}>
        <primitive object={nodes._rootJoint} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MSM_Base_0000_001_SM_Base_0000_MAT_CarPaint_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[-1, -1, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_00_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_00_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_01_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_01_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_02_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_02_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_03_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_03_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_04_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_04_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_05_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_05_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_06_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_06_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_07_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_07_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_08_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_08_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_09_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_09_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_10_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_10_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_11_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_11_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_12_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_12_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_13_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_13_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_14_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_14_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MSM_Base_0000_001_SM_Base_0000_MAT_CarPaint1_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_15_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_16_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_17_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_17_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_18_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_18_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MSM_Base_0000_001_SM_Base_0000_MAT_CarPaint2_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_19_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_19_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_20_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_20_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_21_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MSM_Base_0000_001_SM_Base_0000_MAT_CarPaint3_MMAT_Details_EXT1_0.geometry}
          material={materials.MMAT_Details_EXT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_22_MMAT_Details_EXT1_0.geometry}
          material={materials.MMAT_Details_EXT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MSM_Base_0000_001_SM_Base_0000_MAT_CarPaint4_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_23_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_21_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_24_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_22_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_25_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_23_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_26_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_24_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_27_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_25_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_28_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_26_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_29_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_27_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_30_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_28_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_31_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_29_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_32_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_30_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_33_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_31_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_34_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_32_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_35_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_33_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_36_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_34_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_37_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_35_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_38_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_36_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_39_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_37_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_40_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_38_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_41_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_39_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_42_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_40_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_43_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_44_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_41_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_45_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_42_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_46_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_47_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_45_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Engine_0000_001_SM_Engine_0000_MAT_Details_MAT_001_MMAT_Details_MAT1_0
              .geometry
          }
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_FrontKit_0000_001_SM_FrontKit_0000_MAT_CarPaint_001_MMAT_CarPaint_010_0
              .geometry
          }
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_FrontKit_0000_001_SM_FrontKit_0000_MAT_CarPaint_002_MMAT_Glass1_0.geometry
          }
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_FrontKit_0000_001_SM_FrontKit_0000_MAT_CarPaint_003_MMAT_Lights1_0.geometry
          }
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_FrontKit_0000_001_SM_FrontKit_0000_MAT_CarPaint_004_MMAT_Details_EXT1_0
              .geometry
          }
          material={materials.MMAT_Details_EXT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_FrontKit_0000_001_SM_FrontKit_0000_MAT_CarPaint_005_MMAT_Details_MAT1_0
              .geometry
          }
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_FrontKit_0000_001_SM_FrontKit_0000_MAT_CarPaint_006_MMAT_Details_Grid_02_0
              .geometry
          }
          material={materials.MMAT_Details_Grid_02}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Hood_0000_001_SM_Hood_0000_MAT_CarPaint_002_MMAT_CarPaint_010_0.geometry
          }
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Hood_0000_001_SM_Hood_0000_MAT_CarPaint_003_MMAT_Details_EXT1_0.geometry
          }
          material={materials.MMAT_Details_EXT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Hood_0000_001_SM_Hood_0000_MAT_CarPaint_004_MMAT_Details_MAT1_0.geometry
          }
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Interior_0000_001_SM_Interior_0000_MAT_CarPaint_003_MMAT_CarPaint_010_0
              .geometry
          }
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_46_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_50_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_00_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_47_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_51_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_01_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_48_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_52_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_02_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_53_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_03_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_54_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_04_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_49_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_55_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_05_MMAT_CarPaint_010_0.geometry}
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_50_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_56_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_00_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_08_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Interior_0000_001_SM_Interior_0000_MAT_CarPaint_005_MMAT_Details_INT1_0
              .geometry
          }
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_52_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_58_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_09_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_53_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_10_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_59_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_02_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_11_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_03_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_60_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_04_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_12_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_54_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_05_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_61_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_06_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_13_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_55_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_07_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_62_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_08_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_56_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_63_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_57_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_64_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_14_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_58_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_15_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_65_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_16_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_09_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_17_MMAT_Details_INT1_0.geometry}
          material={materials.MMAT_Details_INT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Interior_0000_001_SM_Interior_0000_MAT_CarPaint_006_MMAT_Lights1_0.geometry
          }
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_59_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_66_MMAT_Lights1_0.geometry}
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_Interior_0000_001_SM_Interior_0000_MAT_CarPaint_007_MMAT_Details_MAT1_0
              .geometry
          }
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_60_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_18_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_10_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_19_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_67_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_20_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_61_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_21_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_62_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_22_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_63_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_23_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_68_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_24_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_69_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_25_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_70_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_26_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_71_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_27_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_64_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_28_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_11_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_29_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_72_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_30_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_65_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_31_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_12_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_32_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_73_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_13_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_33_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_66_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_34_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_14_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_35_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_74_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_15_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_36_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_67_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_16_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_37_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_75_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_17_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_38_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_68_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_39_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_76_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_18_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_40_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_69_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_77_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_41_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_70_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_42_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_78_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_43_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_71_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_79_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_44_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_72_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_80_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_19_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_45_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_20_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_46_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_73_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_21_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_47_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_81_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_48_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_22_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_49_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_74_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_23_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_50_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_82_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_51_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_75_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_24_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_52_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_83_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_76_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_53_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_R_84_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_54_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_SteeringWheel_25_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MD_Body_55_MMAT_Details_MAT1_0.geometry}
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_RearKit_0000_001_SM_RearKit_0000_MAT_CarPaint_004_MMAT_CarPaint_010_0.geometry
          }
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_RearKit_0000_001_SM_RearKit_0000_MAT_CarPaint_005_MMAT_Glass1_0.geometry
          }
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_RearKit_0000_001_SM_RearKit_0000_MAT_CarPaint_006_MMAT_Lights1_0.geometry
          }
          material={materials.MMAT_Lights1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_RearKit_0000_001_SM_RearKit_0000_MAT_CarPaint_007_MMAT_Details_EXT1_0.geometry
          }
          material={materials.MMAT_Details_EXT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.MSM_RearKit_0000_001_SM_RearKit_0000_MAT_CarPaint_008_MMAT_Details_MAT1_0.geometry
          }
          material={materials.MMAT_Details_MAT1}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .MSM_Root_Mercedes_G63_2019_001_SM_Root_Mercedes_G63_2019_MAT_CarPaint_005_MMAT_CarPaint_010_0
              .geometry
          }
          material={materials.MMAT_CarPaint_010}
          position={[0, 0.32, 0.019]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MANC_Door_L_77_MMAT_Glass1_0.geometry}
          material={materials.MMAT_Glass1}
          position={[0, 0.32, 0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.carbon_MMAT_Carbon1_0.geometry}
          material={materials.MMAT_Carbon1}
          position={[0, 0.32, 0.019]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/3dassets/cars/2025_mercedes-benz_g-class_amg_g_63.glb")
