/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bmw-i8-4b143b95aec045bf8912d99662f8d580
Title: BMW I8
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bmw(props) {
  const { nodes, materials } = useGLTF('/3dassets/cars/bmw_i8.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.008}>
        <group
          position={[92.585, -32.235, 155.753]}
          rotation={[-Math.PI / 2, 0, -0.297]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_bhrome_d_0.geometry}
            material={materials.bhrome_d}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_bhrome_0.geometry}
            material={materials.bhrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_chrome_0.geometry}
            material={materials.chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_disc_0.geometry}
            material={materials.disc}
          />
        </group>
        <group position={[84.53, -33.355, -149.09]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel001_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel001_bhrome_d_0.geometry}
            material={materials.bhrome_d}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel001_bhrome_0.geometry}
            material={materials.bhrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel001_chrome_0.geometry}
            material={materials.chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel001_disc_0.geometry}
            material={materials.disc}
          />
        </group>
        <group
          position={[-92.588, -32.235, 155.753]}
          rotation={[-Math.PI / 2, 0, -0.297]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel002_tire_0.geometry}
            material={materials.tire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel002_bhrome_d_0.geometry}
            material={materials.bhrome_d}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel002_bhrome_0.geometry}
            material={materials.bhrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel002_chrome_0.geometry}
            material={materials.chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel002_disc_0.geometry}
            material={materials.disc}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['mesh_glass-red_0'].geometry}
          material={materials['glass-red']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_cali_0.geometry}
          material={materials.cali}
          position={[84.901, -32.268, 153.336]}
          rotation={[-Math.PI / 2, 0, -0.297]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert001_cali_0.geometry}
          material={materials.cali}
          position={[84.53, -33.355, -149.09]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert002_cali_0.geometry}
          material={materials.cali}
          position={[-92.588, -32.235, 155.753]}
          rotation={[-Math.PI / 2, 0, -0.297]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh001_paint_0.geometry}
          material={materials.paint}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_bhrome_0.geometry}
          material={materials.bhrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_light_e_0.geometry}
          material={materials.light_e}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh004_glack_0.geometry}
          material={materials.glack}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh005_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh006_mlack_0.geometry}
          material={materials.mlack}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh007_blu_0.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh008_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh009_glass_l_0.geometry}
          material={materials.glass_l}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh010_bumpa_0.geometry}
          material={materials.bumpa}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/cars/bmw_i8.glb')
